easy_admin:
    site_name: 'Dumpsters-Back'
    design: 
        brand_color: 'rgba(26, 188, 156, 0.85)'
        menu:
        - label: 'Gérer'
          icon: 'tools'
          children:
            - {entity: 'Category', icon: 'list', label: 'Catégorie'}
            - {entity: 'PostStatus', icon: 'check', label: 'Statut'}
            - {entity: 'Visibility', icon: 'eye', label: 'Visibilité'}
            - {entity: 'WearCondition', icon: 'question', label: 'Usure'}
    entities:
        PostStatus:
          class: App\Entity\PostStatus
        Category:
          class: App\Entity\Category
        Visibility:
          class: App\Entity\Visibility
        WearCondition:
          class: App\Entity\WearCondition
